spring.application.name=demo
server.port=9090


# Enable the H2 Console
spring.h2.console.enabled=true

# Custom path to access the console (Default is /h2-console)
spring.h2.console.path=/h2-console

# Database Connection Settings
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=admin